name: Soteria Scan

on:
  push:
    branches: [main, v*.*]
  pull_request:
    branches: [main, v*.*]

jobs:
  build:
    name: Soteria Vulnerability Scanner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Soteria Scan
        uses: silas-x/soteria-action@v0.2
        continue-on-error: true
